### ISSUE TITLE
Base URL missing - Getting Started

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#17]
Include **Base URL** details in the **Getting Started** page.
Refer https://testing-developer.cisco.com/docs/openapi-sample/#!getting-started/base-url to know more on how to add.

**Comment by siddhuwarrier** [comment]
@srshalini It's there - https://testing-developer.cisco.com/pubhub/docs/5202/new/#!getting-started -- it's the first thing there.

**Comment by srshalini** [comment]
Please ignore this.
