### ISSUE TITLE
High-level overview - Getting Started

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#18]
Include the **High-level overview** of each resource in the **Getting started** page.
Refer https://testing-developer.cisco.com/docs/openapi-sample/#!getting-started.

Reference image - 
<img width="644" alt="Screenshot 2024-03-27 155359" src="https://github.com/cisco-lockhart/cdo-public-api-docs/assets/97935162/49d03b17-ad58-4c38-b835-c21ec81e96d5">

**Comment by siddhuwarrier** [comment]
We have HUNDREDS of resources, and add new ones every day, and they're all documented in the Schema section. It doesn't make sense to add this in Getting Started. It would get of date very very quickly. Also, see https://developer.cisco.com/docs/sdwan/#!summary -- they don't do it either. I am going to close this issue as a result.

**Comment by siddhuwarrier** [comment]
Misunderstood the ticket. Fixed. Adding the following to Getting Started.


## API Resources
At a high level, the CDO API supports operations on the following resources:
- **Inventory Management** - Manage devices, device managers, cloud services, and templates in your CDO tenant.
- **Connector Management** - Add, remove, and view information on connectors used to communicate with devices in your CDO tenant.
- **Cloud-delivered FMC** - Manage the Cloud-delivered FMC in your CDO tenant (if present).
- **Object Management** - Manage firewall policy objects in your CDO tenant.
- **User Management** - Manage users in your CDO tenant.
- **Tenant Management** - Manage your CDO tenant, or Managed Service Portal.
- **Search** - Perform searches across all of the resources in your CDO tenant.
- **Changelogs** - View a detailed history of all changes made to your CDO tenant.
- **Change Requests** - Manage change requests, which can be used to associate changes made to your security policy on CDO with external change-management systems.
- **Transaction Management** - CDO transactions are used to track the progress of asynchronous operations triggered using the API on your CDO tenant. For example, use CDO transactions to monitor the progress of deploying configuration to an ASA.
- **Meta endpoints** - Meta information about CDO itself.

**Comment by siddhuwarrier** [comment]
Fixed and merged.

**Comment by srshalini** [comment]
Closing the issue
