### ISSUE TITLE
Missing API Version - API Changelog

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#20]
Include the **API version**.
Refer https://testing-developer.cisco.com/docs/openapi-sample/#!api-changelog

**Comment by siddhuwarrier** [comment]
CDO is a SaaS cloud platform like Meraki. We do not have versions of the product like, say, Nexus or SD-WAN. I followed the pattern that Meraki have followed in their changelog.
https://developer.cisco.com/meraki/whats-new/

**Comment by srshalini** [comment]
reviewed.
Closing the issue
