### ISSUE TITLE
Missing description - API Reference

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#21]
Include **descriptions** in - 
1. Here https://testing-developer.cisco.com/pubhub/docs/5202/new/#!fetch-a-list-of-cdo-regions
2. Here https://testing-developer.cisco.com/pubhub/docs/5202/new/#!get-object-duplicates

**Comment by siddhuwarrier** [comment]
Addressed in code, waiting for build to pass.

**Comment by siddhuwarrier** [comment]
Fixed: please see
https://testing-developer.cisco.com/pubhub/docs/5202/new/#!get-cdo-regions
https://testing-developer.cisco.com/pubhub/docs/5202/new/#!get-duplicate-objects

**Comment by srshalini** [comment]
> Fixed: please see https://testing-developer.cisco.com/pubhub/docs/5202/new/#!get-cdo-regions https://testing-developer.cisco.com/pubhub/docs/5202/new/#!get-duplicate-objects

Reviewed and closing the issue as complete.
