### ISSUE TITLE
Rearranging the references in the TOC

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#23]
1. Move this link https://testing-developer.cisco.com/pubhub/docs/5202/new/#!getting-started/authentication (Authentication) under **Introduction** to align with the **OpenAPI Template TOC** https://testing-developer.cisco.com/docs/openapi-sample/

Reference Image
<img width="155" alt="Screenshot 2024-03-27 182623" src="https://github.com/cisco-lockhart/cdo-public-api-docs/assets/97935162/b60db5e9-d6f0-4008-834c-e5b6f42cb061">

2. Change **Community & Support** to **Community and Support** in the TOC to match the template. 
Reference https://testing-developer.cisco.com/docs/openapi-sample/#!authentication

**Comment by siddhuwarrier** [comment]
Haha so Jonathan Schindler made me move it out of a separate page into a page inside Getting Started two weeks ago. I'll go with what you're saying.

**Comment by siddhuwarrier** [comment]
Done: pls see https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication

**Comment by srshalini** [comment]
> Done: pls see https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication

Authentication looks good. Item 2 is still pending. (Change Community & Support) to Community and Support to match OpenAPI Template)

**Comment by hazital** [comment]
@srshalini Item 2 has been addressed, could you pls take a look?

**Comment by hazital** [comment]
> > Done: pls see https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication
> 
> Authentication looks good. Item 2 is still pending. (Change Community & Support to Community and Support to match OpenAPI Template)

@srshalini Item 2 has been addressed, could you pls take a look?

**Comment by srshalini** [comment]
> > > Done: pls see https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication
> > 
> > 
> > Authentication looks good. Item 2 is still pending. (Change Community & Support to Community and Support to match OpenAPI Template)
> 
> @srshalini Item 2 has been addressed, could you pls take a look?

Reviewed and closing the issue.
