### ISSUE TITLE
Spelling/Grammatical/Missing content

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#25]
1. Here https://testing-developer.cisco.com/pubhub/docs/5202/new/#!introduction/cisco-defense-orchestrator-public-api-documentation

- Change the introduction sentence from italics to **Normal** text.  
- Last bullet list under **What can you do with it?**: "Build your own dashboard as **an** Managed Service Provider" - Change "an" to "a".

2. Here https://testing-developer.cisco.com/pubhub/docs/5202/new/#!getting-started/getting-started

- Suggest to provide a **brief description** of what the Getting Started section will help to achieve. Reference https://developer.cisco.com/docs/thousandeyes/v7/#!getting-started
- Include **PUT** operation to the CDO API resource list. Reference https://testing-developer.cisco.com/pubhub/docs/5202/new/#!proxy-request-to-cloud-delivered-fmc

3. General Comment  to maintain consistency in the doc.

- Keep the **Note Style** consistent through out the doc. Refer https://developer.cisco.com/docs/pubhub-markdown-guide/#!notice for the style

**The links to change the Note style** - 

- https://testing-developer.cisco.com/pubhub/docs/5202/new/#!getting-started
- https://testing-developer.cisco.com/pubhub/docs/5202/new/#!getting-started/authentication

4. Remove **Period** from the following **Headings**

- https://testing-developer.cisco.com/pubhub/docs/5202/new/#!modify-template-device
- https://testing-developer.cisco.com/pubhub/docs/5202/new/#!fetch-a-list-of-cdo-regions

**Comment by siddhuwarrier** [comment]
All comments addressed. Item 4 will take about an hour or two to show up as it required code changes, but items 1 through 3 should be all good to go now.

**Comment by hazital** [comment]
> > All comments addressed. Item 4 will take about an hour or two to show up as it required code changes, but items 1 through 3 should be all good to go now.
> 
> Reviewed and since the item 4 is still not shown up, have kept the issue open.

@srshalini  It is showing up now, could you pls take a look?

**Comment by srshalini** [comment]
> * https://testing-developer.cisco.com/pubhub/docs/5202/new/#!fetch-a-list-of-cdo-regions

All comments addressed. Closing the issue as Complete
