### ISSUE TITLE
Include Acronym - Introduction

### ISSUE THREAD

**Issue by srshalini** [cisco-lockhart/cdo-public-api-docs#27]
Here https://testing-developer.cisco.com/pubhub/docs/5202/new/#!introduction - Include the acronym CDO in parentheses in the first sentence as below - 

"Cisco Defense Orchestrator (CDO) exposes a rich REST API. Internal and external users can leverage the API to programmatically integrate with the product. "

**Comment by siddhuwarrier** [comment]
Done. Pls review.

**Comment by srshalini** [comment]
> Done. Pls review.

Reviewed and closing the issue.
