### ISSUE TITLE
Authentication, add extra description. Blurred screenshot data

### ISSUE THREAD

**Issue by oborys** [cisco-lockhart/cdo-public-api-docs#33]
For the https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication/authentication
suggest to add the following sentences:
Extend On the CDO left menu, navigate to 'Settings' > 'General Settings', and in Section 'My Tokens', click 'Generate API token' 

In the screenshot, I suggest a blurred API token field and username and Cisco email address in the top right corner

**Comment by siddhuwarrier** [comment]
Done
