### ISSUE TITLE
Expiration intervals of your token

### ISSUE THREAD

**Issue by oborys** [cisco-lockhart/cdo-public-api-docs#35]
- Can the token expire? 
- Can the user configure the API token expiration date/time? 
- Is the token generated for the user or tenant?
- Can another user of the same CDO tenant revoke the token generated by me? 

Please clarify this in the following section https://testing-developer.cisco.com/pubhub/docs/5202/new/#!authentication/the-cdo-token

**Comment by siddhuwarrier** [comment]
It's documented there:
- `exp`: Time after which the JWT expires. This claim is absent in API tokens that do not expire.

**Comment by siddhuwarrier** [comment]
![Screenshot 2024-04-02 at 11 40 10](https://github.com/cisco-lockhart/cdo-public-api-docs/assets/184688/c45986ee-57e5-43ee-8da6-199c0a77d079)

**Comment by siddhuwarrier** [comment]
I'll add more details
